trigger:
  - azure-pipelines-neo

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: cpi-neo

# https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/container-phases
resources:
  containers:
    - container: flashpipe-lite
      image: engswee/flashpipe:2.2.1-lite

jobs:
  - job: build
    container: flashpipe-lite
    steps:
      # Upload/Update design time
      - bash: /usr/bin/update_designtime_artifact.sh
        displayName: 'Update/Upload Groovy XML Transformation to design time'
        env:
          HOST_TMN: $(neo-host-tmn)
          HOST_OAUTH: $(neo-oauth-host)
          HOST_OAUTH_PATH: '/oauth2/api/v1/token'
          OAUTH_CLIENTID: $(neo-client-id)
          OAUTH_CLIENTSECRET: $(neo-client-secret)
          IFLOW_ID: GroovyXMLTransformation
          IFLOW_NAME: "Groovy XML Transformation"
          PACKAGE_ID: FlashPipeDemo
          PACKAGE_NAME: "FlashPipe Demo"
          GIT_SRC_DIR: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation"
      # Deploy runtime
      - bash: /usr/bin/deploy_runtime_artifact.sh
        displayName: 'Deploy Groovy XML Transformation to runtime'
        env:
          HOST_TMN: $(neo-host-tmn)
          HOST_OAUTH: $(neo-oauth-host)
          HOST_OAUTH_PATH: '/oauth2/api/v1/token'
          OAUTH_CLIENTID: $(neo-client-id)
          OAUTH_CLIENTSECRET: $(neo-client-secret)
          IFLOW_ID: GroovyXMLTransformation