trigger:
  - azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: cpi-dev
  - group: cpi-prod

# https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/container-phases
resources:
  containers:
    - container: flashpipe
      image: engswee/flashpipe:2.x.x
    - container: flashpipe-lite
      image: engswee/flashpipe:2.x.x-lite

jobs:
  - job: build
    container: flashpipe
    steps:
      # Local unit testing
      # https://docs.microsoft.com/azure/devops/pipelines/tasks/build/maven
      - task: Maven@3
        displayName: 'Local unit test with Maven'
        inputs:
          goals: 'test'
          options: '-s /usr/share/maven/ref/settings-docker.xml'
      # Upload/Update design time
      - bash: /usr/bin/update_designtime_artifact.sh
        displayName: 'Update/Upload Groovy XML Transformation to design time'
        env:
          HOST_TMN: $(dev-host-tmn)
          HOST_OAUTH: $(dev-oauth-host)
          OAUTH_CLIENTID: $(dev-client-id)
          OAUTH_CLIENTSECRET: $(dev-client-secret)
          IFLOW_ID: GroovyXMLTransformation
          IFLOW_NAME: "Groovy XML Transformation"
          PACKAGE_ID: FlashPipeDemo
          PACKAGE_NAME: "FlashPipe Demo"
          GIT_SRC_DIR: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation"
      - bash: /usr/bin/update_designtime_artifact.sh
        displayName: 'Update/Upload INVOIC02 to Invoice XML to design time'
        env:
          HOST_TMN: $(dev-host-tmn)
          HOST_OAUTH: $(dev-oauth-host)
          OAUTH_CLIENTID: $(dev-client-id)
          OAUTH_CLIENTSECRET: $(dev-client-secret)
          IFLOW_ID: INVOIC02_to_Invoice_XML
          IFLOW_NAME: "INVOIC02 to Invoice XML"
          PACKAGE_ID: FlashPipeDemo
          PACKAGE_NAME: "FlashPipe Demo"
          GIT_SRC_DIR: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML"
      # Deploy runtime
      - bash: /usr/bin/deploy_runtime_artifact.sh
        displayName: 'Deploy Groovy XML Transformation to runtime'
        env:
          HOST_TMN: $(dev-host-tmn)
          HOST_OAUTH: $(dev-oauth-host)
          OAUTH_CLIENTID: $(dev-client-id)
          OAUTH_CLIENTSECRET: $(dev-client-secret)
          IFLOW_ID: GroovyXMLTransformation
      - bash: /usr/bin/deploy_runtime_artifact.sh
        displayName: 'Deploy INVOIC02 to Invoice XML to runtime'
        env:
          HOST_TMN: $(dev-host-tmn)
          HOST_OAUTH: $(dev-oauth-host)
          OAUTH_CLIENTID: $(dev-client-id)
          OAUTH_CLIENTSECRET: $(dev-client-secret)
          IFLOW_ID: INVOIC02_to_Invoice_XML
      # Publish Pipeline artifact
      - publish: $(System.DefaultWorkingDirectory)
        artifact: GitRepo
  - deployment: deploy_qa
    container: flashpipe-lite
    dependsOn: build
    environment: cpi_dev
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: GitRepo
                path: $(Build.SourcesDirectory)/
            # Upload/Update design time
            - bash: /usr/bin/update_designtime_artifact.sh
              displayName: 'Update/Upload Groovy XML Transformation to design time'
              env:
                HOST_TMN: $(dev-host-tmn)
                HOST_OAUTH: $(dev-oauth-host)
                OAUTH_CLIENTID: $(dev-client-id)
                OAUTH_CLIENTSECRET: $(dev-client-secret)
                IFLOW_ID: GroovyXMLTransformation_QA
                IFLOW_NAME: "Groovy XML Transformation QA"
                PACKAGE_ID: FlashPipeDemoQA
                PACKAGE_NAME: "FlashPipe Demo QA"
                GIT_SRC_DIR: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation"
                MANIFEST_FILE: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation/QA/MANIFEST.MF"
                PARAM_FILE: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation/QA/parameters.prop"
            - bash: /usr/bin/update_designtime_artifact.sh
              displayName: 'Update/Upload INVOIC02 to Invoice XML to design time'
              env:
                HOST_TMN: $(dev-host-tmn)
                HOST_OAUTH: $(dev-oauth-host)
                OAUTH_CLIENTID: $(dev-client-id)
                OAUTH_CLIENTSECRET: $(dev-client-secret)
                IFLOW_ID: INVOIC02_to_Invoice_XML_QA
                IFLOW_NAME: "INVOIC02 to Invoice XML QA"
                PACKAGE_ID: FlashPipeDemoQA
                PACKAGE_NAME: "FlashPipe Demo QA"
                GIT_SRC_DIR: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML"
                MANIFEST_FILE: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML/QA/MANIFEST.MF"
                PARAM_FILE: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML/QA/parameters.prop"
            # Deploy runtime
            - bash: /usr/bin/deploy_runtime_artifact.sh
              displayName: 'Deploy Groovy XML Transformation to runtime'
              env:
                HOST_TMN: $(dev-host-tmn)
                HOST_OAUTH: $(dev-oauth-host)
                OAUTH_CLIENTID: $(dev-client-id)
                OAUTH_CLIENTSECRET: $(dev-client-secret)
                IFLOW_ID: GroovyXMLTransformation_QA
            - bash: /usr/bin/deploy_runtime_artifact.sh
              displayName: 'Deploy INVOIC02 to Invoice XML to runtime'
              env:
                HOST_TMN: $(dev-host-tmn)
                HOST_OAUTH: $(dev-oauth-host)
                OAUTH_CLIENTID: $(dev-client-id)
                OAUTH_CLIENTSECRET: $(dev-client-secret)
                IFLOW_ID: INVOIC02_to_Invoice_XML_QA
  - deployment: deploy_prod
    container: flashpipe-lite
    dependsOn: deploy_qa
    environment: cpi_prod
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: GitRepo
                path: $(Build.SourcesDirectory)/
            # Upload/Update design time
            - bash: /usr/bin/update_designtime_artifact.sh
              displayName: 'Update/Upload Groovy XML Transformation to design time'
              env:
                HOST_TMN: $(prod-host-tmn)
                HOST_OAUTH: $(prod-oauth-host)
                OAUTH_CLIENTID: $(prod-client-id)
                OAUTH_CLIENTSECRET: $(prod-client-secret)
                IFLOW_ID: GroovyXMLTransformation
                IFLOW_NAME: "Groovy XML Transformation"
                PACKAGE_ID: FlashPipeDemo
                PACKAGE_NAME: "FlashPipe Demo"
                GIT_SRC_DIR: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation"
                PARAM_FILE: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation/PROD/parameters.prop"
            - bash: /usr/bin/update_designtime_artifact.sh
              displayName: 'Update/Upload INVOIC02 to Invoice XML to design time'
              env:
                HOST_TMN: $(prod-host-tmn)
                HOST_OAUTH: $(prod-oauth-host)
                OAUTH_CLIENTID: $(prod-client-id)
                OAUTH_CLIENTSECRET: $(prod-client-secret)
                IFLOW_ID: INVOIC02_to_Invoice_XML
                IFLOW_NAME: "INVOIC02 to Invoice XML"
                PACKAGE_ID: FlashPipeDemo
                PACKAGE_NAME: "FlashPipe Demo"
                GIT_SRC_DIR: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML"
                PARAM_FILE: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML/PROD/parameters.prop"
            # Deploy runtime
            - bash: /usr/bin/deploy_runtime_artifact.sh
              displayName: 'Deploy Groovy XML Transformation to runtime'
              env:
                HOST_TMN: $(prod-host-tmn)
                HOST_OAUTH: $(prod-oauth-host)
                OAUTH_CLIENTID: $(prod-client-id)
                OAUTH_CLIENTSECRET: $(prod-client-secret)
                IFLOW_ID: GroovyXMLTransformation
            - bash: /usr/bin/deploy_runtime_artifact.sh
              displayName: 'Deploy INVOIC02 to Invoice XML to runtime'
              env:
                HOST_TMN: $(prod-host-tmn)
                HOST_OAUTH: $(prod-oauth-host)
                OAUTH_CLIENTID: $(prod-client-id)
                OAUTH_CLIENTSECRET: $(prod-client-secret)
                IFLOW_ID: INVOIC02_to_Invoice_XML