# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: cpi-cicd-pipeline
on:
  workflow_dispatch:
  push:
    branches:
      - github-actions-simulation

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:2.x.x 
    env:
      HOST_TMN: ${{ secrets.NEO_HOST_TMN }}
      BASIC_USERID: ${{ secrets.NEO_USER_ID }}
      BASIC_PASSWORD: ${{ secrets.NEO_PASSWORD }}
      PACKAGE_ID: FlashPipeDemo
      PACKAGE_NAME: "FlashPipe Demo"
    steps:
      - name: 'Checkout Git repository'
        uses: actions/checkout@v2
      - name: 'Local unit test with Maven'
        run: mvn clean test -s /usr/share/maven/ref/settings-docker.xml
      # Set environment variable for source directory of IFlow
      - name: 'Set environment variables for update_designtime_artifact.sh'
        run: |
          echo "GIT_SRC_DIR=$GITHUB_WORKSPACE/FlashPipe Demo/Groovy XML Transformation" >> $GITHUB_ENV
      # Upload/Update design time
      - name: 'Update/Upload Groovy XML Transformation to design time'
        run: /usr/bin/update_designtime_artifact.sh
        shell: bash
        env:
          IFLOW_ID: GroovyXMLTransformation
          IFLOW_NAME: "Groovy XML Transformation"
      # Set environment variable for source directory of IFlow
      - name: 'Set environment variables for update_designtime_artifact.sh'
        run: |
          echo "GIT_SRC_DIR=$GITHUB_WORKSPACE/FlashPipe Demo/INVOIC02_to_Invoice_XML" >> $GITHUB_ENV
      # Upload/Update design time
      - name: 'Update/Upload INVOIC02_Message_Mapping to design time'
        run: /usr/bin/update_designtime_artifact.sh
        shell: bash
        env:
          IFLOW_ID: INVOIC02_Message_Mapping
          IFLOW_NAME: "INVOIC02 Message Mapping"
      - name: 'Simulation test with Maven'
        run: mvn clean verify -Dskip.unit.tests -s /usr/share/maven/ref/settings-docker.xml
      # Deploy runtime
      - name: 'Deploy IFlows to runtime'
        run: /usr/bin/deploy_runtime_artifact.sh
        shell: bash
        env:
          IFLOW_ID: GroovyXMLTransformation,INVOIC02_Message_Mapping
